# Generated by Django 4.2.1 on 2023-05-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/default.png', null=True, upload_to='profile_picture'),
        ),
    ]
